name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./my-app

      - name: Build with Next.js
        run: npm run build
        working-directory: ./my-app

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: 'next-js-project'
          directory: 'my-app/out'
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # ✅ 使用密鑰引用
